const express = require('express');
const multer = require('multer');
const cors = require('cors');
const fs = require('fs');
const path = require('path');
const { createClient } = require('@supabase/supabase-js');

require('dotenv').config();

// Initialize Supabase Client (Service Role for server-side privileged access)
const SUPABASE_URL = 'https://nqtqboeddlopocqnsblz.supabase.co';
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY || 'sb_publishable_NK9Yw0mUpVTo5btwnp8d7A_2ZI4efVV';
const supabaseClient = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

// Admin Credentials (Move to .env for production!)
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'drinterface2024';


const app = express();
const PORT = process.env.PORT || 3000;

// Allow requests from the main Godaddy domain, Render URL itself, and localhost for dev
const allowedOrigins = [
    'http://localhost:3000',
    'http://localhost:5500', 
    'http://127.0.0.1:5500',
    'https://drinterface.com',
    'https://www.drinterface.com'
];

app.use(cors({
    origin: function(origin, callback){
        return callback(null, true);
    }
}));
app.use(express.json());


// Load valid users from firebase-config.js (Mock approach for local validation if needed)

const storage = multer.memoryStorage();
const upload = multer({ storage: storage });

const GAMES_DATA_PATH = path.join(__dirname, '../scripts/gamesData.js');
const ROOT_PROJECTS_DATA_PATH = path.join(__dirname, '../scripts/projectsData.js');

// Helper to read JS object files
function readJsData(filePath, varName) {
    if (!fs.existsSync(filePath)) return null;
    let content = fs.readFileSync(filePath, 'utf8');
    const regex = new RegExp(`const\\s+${varName}\\s*=\\s*(\\[[\\s\\S]*?\\]|\\{[\\s\\S]*?\\})\\s*;`);
    const match = content.match(regex);
    if (match && match[1]) {
        try {
            return Function('"use strict";return (' + match[1] + ')')();
        } catch (e) {
            console.error("Parse error in", filePath, e);
            return null;
        }
    }
    return null;
}

// ──────────────────────────────────────────────────────────────────
// API: Admin Login (Secure)
// ──────────────────────────────────────────────────────────────────
app.post('/api/admin/login', (req, res) => {
    const { password } = req.body;
    if (password === ADMIN_PASSWORD) {
        res.json({ success: true, token: 'session_' + Date.now() }); // Simple mock token
    } else {
        res.status(401).json({ success: false, error: 'Incorrect password' });
    }
});

// Helper to write JS object files (Safe for Render)
function writeJsData(filePath, varName, data, isModule = false) {
    try {
        const dir = path.dirname(filePath);
        if (!fs.existsSync(dir)) {
            console.warn(`[FILESYSTEM] Skipping write: Directory ${dir} does not exist.`);
            return;
        }
        let moduleExport = isModule ? `\n\nif (typeof module !== 'undefined' && module.exports) {\n    module.exports = ${varName};\n}` : '';
        const content = `// Auto-generated by Admin CMS\nconst ${varName} = ${JSON.stringify(data, null, 4)};${moduleExport}\n`;
        fs.writeFileSync(filePath, content, 'utf8');
        console.log(`[FILESYSTEM] Sync completed for ${varName}`);
    } catch (e) {
        console.error(`[FILESYSTEM] Error writing ${varName}:`, e.message);
    }
}

// Ensure projectsData.js and gamesData.js exist (Only if directory is present)
const scriptsDir = path.dirname(ROOT_PROJECTS_DATA_PATH);
if (fs.existsSync(scriptsDir)) {
    if (!fs.existsSync(ROOT_PROJECTS_DATA_PATH)) {
        writeJsData(ROOT_PROJECTS_DATA_PATH, 'projectsData', {}, true);
    }
    if (!fs.existsSync(GAMES_DATA_PATH)) {
        writeJsData(GAMES_DATA_PATH, 'gamesData', [], true);
    }
} else {
    console.log("[STORAGE] Not in local dev environment. Skipping local file initialization.");
}


// ──────────────────────────────────────────────────────────────────
// API: GET All Projects — from Supabase
// ──────────────────────────────────────────────────────────────────
app.get('/api/projects', async (req, res) => {
    const { data, error } = await supabaseClient
        .from('projects')
        .select('*')
        .order('sort_order', { ascending: false });

    if (error) return res.status(500).json({ error: error.message });

    // Transform flat Supabase rows into the shape admin.html expects
    const allProjects = {};
    (data || []).forEach(row => {
        allProjects[row.id] = {
            id: row.id,
            thumbnailInfo: {
                Name: row.name,
                Type: row.type,
                Image: row.image,
                Url: row.url || (row.type === 'ui-ux' ? `project.html?id=${row.id}` : ''),
                Tags: row.tags || [],
                FigmaLink: row.figma_url,
                Owners: (row.owners || []).join(', '),
                Tools: row.tools || []
            },
            caseStudyContent: {
                title: row.name,
                introText: row.intro_text || '',
                assets: row.assets || {}
            }
        };
    });
    res.json(allProjects);
});

// ──────────────────────────────────────────────────────────────────
// API: Save / Create a Project — into Supabase
// ──────────────────────────────────────────────────────────────────
app.post('/api/project', async (req, res) => {
    try {
        const { id, thumbnailInfo, caseStudyContent } = req.body;
        if (!id) return res.status(400).json({ error: 'Missing project ID' });

        const row = {
            id,
            name: thumbnailInfo.Name,
            type: thumbnailInfo.Type || 'ui-ux',
            image: thumbnailInfo.Image || null,
            url: thumbnailInfo.Type === 'ui-ux' ? `project.html?id=${id}` : (thumbnailInfo.Url || null),
            tags: thumbnailInfo.Tags || [],
            figma_url: thumbnailInfo.FigmaLink || null,
            owners: thumbnailInfo.Owners ? thumbnailInfo.Owners.split(',').map(o => o.trim()) : [],
            tools: thumbnailInfo.Tools || [],
            intro_text: caseStudyContent?.introText || '',
            assets: caseStudyContent?.assets || {}
        };

        const { error } = await supabaseClient.from('projects').upsert(row, { onConflict: 'id' });
        if (error) throw error;

        res.json({ success: true, message: 'Project saved to Supabase' });
    } catch (e) {
        console.error(e);
        res.status(500).json({ error: e.message });
    }
});

// ──────────────────────────────────────────────────────────────────
// API: Delete a project — from Supabase
// ──────────────────────────────────────────────────────────────────
app.delete('/api/project/:id', async (req, res) => {
    try {
        const id = req.params.id;
        console.log(`--> [DELETE API] Deleting project: ${id}`);

        const { error } = await supabaseClient.from('projects').delete().eq('id', id);
        if (error) throw error;

        console.log(`--> [DELETE API] Project ${id} deleted from Supabase.`);
        res.json({ success: true });
    } catch (e) {
        console.error('--> [DELETE API] ERROR:', e);
        res.status(500).json({ error: e.message });
    }
});

// ──────────────────────────────────────────────────────────────────
// API: Public Review Submission (bypasses RLS via service key)
// ──────────────────────────────────────────────────────────────────
app.post('/api/submit-review', async (req, res) => {
    try {
        const { project_id, name, rating, comment } = req.body;

        if (!project_id || !name || !rating || !comment) {
            return res.status(400).json({ error: 'Missing required fields: project_id, name, rating, comment' });
        }
        if (typeof rating !== 'number' || rating < 1 || rating > 5) {
            return res.status(400).json({ error: 'Rating must be a number between 1 and 5' });
        }

        const { error } = await supabaseClient
            .from('project_reviews')
            .insert({
                project_id,
                name,
                rating,
                comment,
                status: 'pending',
                thread: []
            });

        if (error) throw error;

        res.json({ success: true, message: 'Review submitted successfully and is pending approval.' });
    } catch (e) {
        console.error('[submit-review] Error:', e);
        res.status(500).json({ error: e.message });
    }
});

// ──────────────────────────────────────────────────────────────────
// API: Submit User Reply to existing review thread (Service Key)
// ──────────────────────────────────────────────────────────────────
app.post('/api/submit-user-reply', async (req, res) => {
    try {
        const { reviewId, text } = req.body;
        if (!reviewId || !text) {
            return res.status(400).json({ error: 'Missing reviewId or text' });
        }

        // 1. Fetch current thread
        const { data: review, error: fetchErr } = await supabaseClient
            .from('project_reviews')
            .select('thread, name')
            .eq('id', reviewId)
            .single();

        if (fetchErr) throw fetchErr;

        // 2. Append user reply
        const updatedThread = [...(review.thread || []), {
            role: 'user',
            text: text,
            timestamp: new Date().toISOString()
        }];

        // 3. Update thread
        const { error: updateErr } = await supabaseClient
            .from('project_reviews')
            .update({ thread: updatedThread })
            .eq('id', reviewId);

        if (updateErr) throw updateErr;

        console.log(`--> [THREAD] User reply added to review ${reviewId}`);
        res.json({ success: true });
    } catch (e) {
        console.error('[submit-user-reply] Error:', e);
        res.status(500).json({ error: e.message });
    }
});

// ──────────────────────────────────────────────────────────────────
// API: Admin Reply to existing review thread (Service Key)
// ──────────────────────────────────────────────────────────────────
app.post('/api/admin-reply', async (req, res) => {
    try {
        const { id, text } = req.body;
        if (!id || !text) {
            return res.status(400).json({ error: 'Missing review id or text' });
        }

        // 1. Fetch current thread
        const { data: review, error: fetchErr } = await supabaseClient
            .from('project_reviews')
            .select('thread')
            .eq('id', id)
            .single();

        if (fetchErr) throw fetchErr;

        // 2. Append admin reply
        const updatedThread = [...(review.thread || []), {
            role: 'admin',
            text: text,
            timestamp: new Date().toISOString()
        }];

        // 3. Update thread
        const { error: updateErr } = await supabaseClient
            .from('project_reviews')
            .update({ thread: updatedThread })
            .eq('id', id);

        if (updateErr) throw updateErr;

        console.log(`--> [THREAD] Admin reply added to review ${id}`);
        res.json({ success: true });
    } catch (e) {
        console.error('[admin-reply] Error:', e);
        res.status(500).json({ error: e.message });
    }
});

// ──────────────────────────────────────────────────────────────────
// API: Public Fetch Approved Reviews (bypasses RLS via service key)
// ──────────────────────────────────────────────────────────────────
app.get('/api/approved-reviews/:project_id', async (req, res) => {
    const { project_id } = req.params;
    const { data, error } = await supabaseClient
        .from('project_reviews')
        .select('*')
        .eq('project_id', project_id)
        .eq('status', 'approved')
        .order('created_at', { ascending: false });
    if (error) return res.status(500).json({ error: error.message });
    res.json(data);
});

// ──────────────────────────────────────────────────────────────────
// API: Reviews (Admin Proxy to bypass RLS)
// ──────────────────────────────────────────────────────────────────
app.get('/api/reviews', async (req, res) => {
    const { data, error } = await supabaseClient
        .from('project_reviews')
        .select('*')
        .order('created_at', { ascending: false });
    if (error) return res.status(500).json({ error: error.message });
    res.json(data);
});

app.put('/api/reviews/:id', async (req, res) => {
    const { id } = req.params;
    const { status, thread } = req.body;
    
    let updateData = {};
    if (status) updateData.status = status;
    if (thread) updateData.thread = thread;

    const { error } = await supabaseClient
        .from('project_reviews')
        .update(updateData)
        .eq('id', id);
    if (error) return res.status(500).json({ error: error.message });
    res.json({ success: true });
});

app.delete('/api/reviews/:id', async (req, res) => {
    const { id } = req.params;
    const { error } = await supabaseClient
        .from('project_reviews')
        .delete()
        .eq('id', id);
    if (error) return res.status(500).json({ error: error.message });
    res.json({ success: true });
});

// ──────────────────────────────────────────────────────────────────
// API: Access Requests (Admin Proxy to bypass RLS)
// ──────────────────────────────────────────────────────────────────
app.get('/api/access_requests', async (req, res) => {
    const { data, error } = await supabaseClient
        .from('access_requests')
        .select('*')
        .order('created_at', { ascending: false });
    if (error) return res.status(500).json({ error: error.message });
    res.json(data);
});

app.delete('/api/access_requests/:id', async (req, res) => {
    const { id } = req.params;
    const { error } = await supabaseClient
        .from('access_requests')
        .delete()
        .eq('id', id);
    if (error) return res.status(500).json({ error: error.message });
    res.json({ success: true });
});

// ──────────────────────────────────────────────────────────────────
// STARTUP: Seed Supabase with existing gamesData.js if table is empty
// ──────────────────────────────────────────────────────────────────
async function seedSupabaseIfEmpty() {
    const { data, error } = await supabaseClient.from('projects').select('id').limit(1);
    if (error || (data && data.length > 0)) return; // Already has data

    console.log('--> [SEED] Supabase projects table is empty. Seeding from gamesData.js...');
    let gamesList = readJsData(GAMES_DATA_PATH, 'gamesData') || [];

    const rows = gamesList.map((g, i) => ({
        id: g.Url && g.Url.includes('?id=') ? g.Url.split('?id=')[1]
            : (g.Name.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 40) + '_' + i),
        name: g.Name,
        type: g.Type || (g.Url && g.Url.startsWith('http') ? 'company' : 'ui-ux'),
        image: g.Image || null,
        url: g.Url || null,
        tags: g.Tags || [],
        figma_url: g.FigmaLink || null,
        owners: g.Owners ? [g.Owners] : [],
        tools: g.Tools || [],
        sort_order: gamesList.length - i,
        intro_text: '',
        assets: {}
    }));

    const { error: insertErr } = await supabaseClient.from('projects').upsert(rows, { onConflict: 'id' });
    if (insertErr) console.error('--> [SEED] Error seeding:', insertErr.message);
    else console.log(`--> [SEED] Successfully seeded ${rows.length} projects into Supabase!`);
}



// Upload endpoint — saves image to Supabase Storage
app.post('/api/upload', upload.single('image'), async (req, res) => {
    console.log("--> [UPLOAD API] Received image upload request.");
    if (!req.file) {
        console.error("--> [UPLOAD API] Error: No file uploaded");
        return res.status(400).json({ error: 'No file uploaded' });
    }

    try {
        const originalName = req.file.originalname.replace(/[^a-zA-Z0-9.\-]/g, '_');
        const filename = `${Date.now()}_${originalName}`;
        console.log(`--> [UPLOAD API] Uploading to Supabase Storage: ${filename} (${req.file.size} bytes)`);

        // Upload the file buffer directly to Supabase Storage
        const { data, error } = await supabaseClient.storage
            .from('project-images')
            .upload(filename, req.file.buffer, {
                contentType: req.file.mimetype,
                upsert: false
            });

        if (error) throw error;

        // Get the public URL for the uploaded file
        const { data: urlData } = supabaseClient.storage
            .from('project-images')
            .getPublicUrl(filename);

        const publicUrl = urlData.publicUrl;
        console.log("--> [UPLOAD API] Success! Supabase URL: " + publicUrl);
        res.json({ success: true, url: publicUrl });

    } catch (e) {
        console.error("--> [UPLOAD API] UPLOAD ERROR:", e);
        res.status(500).json({ error: 'Failed to upload to Supabase Storage: ' + e.message });
    }
});

// ──────────────────────────────────────────────────────────────────
// API: Site Feedback (Portfolio-wide Reviews)
// ──────────────────────────────────────────────────────────────────
app.post('/api/submit-feedback', async (req, res) => {
    try {
        const { name, role, rating, comment } = req.body;
        console.log(`--> [FEEDBACK] Received submission from: ${name}`);

        if (!name || !comment) {
            return res.status(400).json({ error: 'Name and comment are required.' });
        }
        
        const initials = name.split(' ').map(w => w[0]).join('').toUpperCase().slice(0, 2);
        
        const feedbackData = {
            name,
            role: role || 'Visitor',
            rating: rating || 5,
            comment,
            avatar_initials: initials,
            status: 'pending'
        };

        const { error } = await supabaseClient.from('site_feedback').insert(feedbackData);
        
        if (error) {
            console.error('--> [FEEDBACK] Supabase Error:', error);
            return res.status(500).json({ error: `Supabase Error: ${error.message} (Code: ${error.code})` });
        }

        res.json({ success: true, message: 'Thank you! Your feedback has been submitted and is awaiting approval.' });
    } catch (e) {
        console.error('--> [FEEDBACK] System Error:', e);
        res.status(500).json({ error: `Internal Server Error: ${e.message}` });
    }
});

app.get('/api/site-feedback', async (req, res) => {
    const { data, error } = await supabaseClient
        .from('site_feedback')
        .select('*')
        .eq('status', 'approved')
        .order('created_at', { ascending: false });
    if (error) return res.status(500).json({ error: error.message });
    res.json(data || []);
});

app.get('/api/admin-feedback', async (req, res) => {
    const { data, error } = await supabaseClient
        .from('site_feedback')
        .select('*')
        .order('created_at', { ascending: false });
    if (error) return res.status(500).json({ error: error.message });
    res.json(data || []);
});

app.put('/api/feedback/:id', async (req, res) => {
    const { id } = req.params;
    const { status } = req.body;
    const { error } = await supabaseClient.from('site_feedback').update({ status }).eq('id', id);
    if (error) return res.status(500).json({ error: error.message });
    res.json({ success: true });
});

app.delete('/api/feedback/:id', async (req, res) => {
    const { id } = req.params;
    const { error } = await supabaseClient.from('site_feedback').delete().eq('id', id);
    if (error) return res.status(500).json({ error: error.message });
    res.json({ success: true });
});

// Add global error handler to catch unseen upload/multer errors
app.use((err, req, res, next) => {
    console.error("--> [EXPRESS ERROR HANDLER] Caught error:", err);
    res.status(500).json({ error: "Internal Server Error", details: err.message });
});

app.listen(PORT, async () => {
    console.log(`🚀 Multi-Project CMS is running on port ${PORT}!`);
    await seedSupabaseIfEmpty();
});
